---
- import_playbook: ka-init/init.yml

- hosts: master
  become: true
  become_user: root
  tasks: []
  roles:
    - { role: kube-master-teardown }


- hosts: nodes
  become: true
  become_user: root
  tasks: []
  roles:
    - { role: kube-nodes-teardown }
